# Generated by Django 4.0.3 on 2022-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
