# Generated by Django 4.0.3 on 2022-05-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgt_app', '0002_alter_subjects_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_mgt_app.courses'),
        ),
    ]
